# Generated by Django 3.2.6 on 2021-08-24 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_likepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
        migrations.AddField(
            model_name='likepost',
            name='post_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likepost',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='likepost',
            constraint=models.UniqueConstraint(fields=('user_id', 'post_id'), name='blog_likes'),
        ),
    ]
