# Generated by Django 3.2.6 on 2021-09-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210824_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
