# Generated by Django 3.2.6 on 2021-09-15 12:47

from django.db import migrations, models
import rest_framework.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(verbose_name=rest_framework.fields.HiddenField),
        ),
    ]
