# Generated by Django 3.2.6 on 2021-08-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('content', models.TextField()),
            ],
        ),
    ]
